version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - IMAGE_TAG=$PROJECT_NAME/$COMPONENT:0.0.1
      - echo Logging in to Amazon ECR...

  build:
    commands:
      - echo Building image tag $IMAGE_TAG
      - docker build -t $IMAGE_TAG .
      - docker tag $IMAGE_TAG $IMAGE_REPOSITORY/$IMAGE_TAG
  post_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-west-2)
      - echo Pushing to $IMAGE_REPOSITORY
      - docker push $IMAGE_REPOSITORY/$IMAGE_TAG
