version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true 
  pre_build:
    commands:
      - env
      - echo Logging in to Amazon ECR...
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPOSITORY/$PROJECT_NAME/$COMPONENT .
  post_build:
    commands:
      - echo Build completed on `date`
      - $CODEBUILD_SRC_DIR_platform/scripts/publish-if-release-tag.sh
