version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  env:
      git-credential-helper: yes

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $COMPONENT:$CODEBUILD_WEBHOOK_HEAD_REF .
  post_build:
    commands:
      - echo Build completed on `date`
      - $CODEBUILD_SRC_DIR_platform/scripts/code-build-git-wrapper.sh https://git-codecommit.us-west-2.amazonaws.com/v1/repos/"$PROJECT_NAME"_"$COMPONENT"
